document.writeln("<!--footer start-->");
document.writeln("    <footer class=\'footer\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("          <div class=\'col-lg-3 col-sm-3 address wow fadeInUp\' data-wow-duration=\'2s\' data-wow-delay=\'.1s\'>");
document.writeln("            <h1>");
document.writeln("              contact info");
document.writeln("            </h1>");
document.writeln("            <address>");
document.writeln("              <p><i class=\'fa fa-globe pr-10\'></i>Shanghai, China </p>");
document.writeln("              <p><i class=\'fa fa-mobile pr-10\'></i>Mobile : (+86)21-34208230 </p>");
// document.writeln("              <p><i class=\'fa fa-phone pr-10\'></i>Fax : +86-21-34204728 </p>");
document.writeln("              <p><i class=\'fa fa-envelope pr-10\'></i>Email :  </br><a href=\"mailto:wuct@cs.sjtu.edu.cn,Frontier_Setter@sjtu.edu.cn\">wuct@cs.sjtu.edu.cn </br> Frontier_Setter@sjtu.edu.cn</a></p>");
// document.writeln("                  ")
document.writeln("            </address>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-lg-3 col-sm-3 wow fadeInUp\' data-wow-duration=\'2s\' data-wow-delay=\'.3s\'>");
document.writeln("            <h1>Supporters</h1>");
document.writeln("			<p><img src=\'img/SJTU.png\' width=\'90%\'></p>");
// document.writeln("			<p><img src=\'img/not decided.png\' width=\'227\' height=\'72\'></p>");
document.writeln("		  </div>");
document.writeln("          <div class=\'col-lg-3 col-sm-3\'>");
document.writeln("            <div class=\'page-footer wow fadeInUp\' data-wow-duration=\'2s\' data-wow-delay=\'.5s\'>");
document.writeln("              <h1>");
document.writeln("                More Informations");
document.writeln("              </h1>");
document.writeln("              <ul class=\'page-footer-list\'>");
document.writeln("                <li>");
document.writeln("                  <i class=\'fa fa-angle-right\'></i>");
document.writeln("                  <a href=\'call-papers.html\'>CFP</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <i class=\'fa fa-angle-right\'></i>");
document.writeln("                  <a href=\'submission.html\'>Submission</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <i class=\'fa fa-angle-right\'></i>");
document.writeln("                  <a href=\'registration.html\'>Registration</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <i class=\'fa fa-angle-right\'></i>");
document.writeln("                  <a href=\'committees.html\'>Committees</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <i class=\'fa fa-angle-right\'></i>");
document.writeln("                  <a href=\'program-summary.html\'>Program</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <i class=\'fa fa-angle-right\'></i>");
document.writeln("                  <a href=\'venue.html\'>Venue</a>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-lg-3 col-sm-3\'>");
document.writeln("            <div class=\'text-footer wow fadeInUp\' data-wow-duration=\'2s\' data-wow-delay=\'.7s\' >");
document.writeln("              <h1>Silver Sponsor</h1>");
document.writeln("			  <p><img src=\'img/aliyun.jpg\' width=\'90%\'></p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </footer>");
document.writeln("    <!-- footer end -->");
document.writeln("    <!--small footer start -->");
document.writeln("    <footer class=\'footer-small\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <div class=\'col-lg-6 col-sm-6 pull-right\'>");
document.writeln("                    <ul class=\'social-link-footer list-unstyled\'>");
// document.writeln("                        <li class=\'wow flipInX\' data-wow-duration=\'2s\' data-wow-delay=\'.3s\'><a href=\'img/QRcode.png\'><i class=\'fa fa-comments\'></i></a></li>");
// document.writeln("                        <li class=\'wow flipInX\' data-wow-duration=\'2s\' data-wow-delay=\'.4s\'><a href=\'http://www.linkedin.com/in/hk-sme-6b297bbb/\'><i class=\'fa fa-linkedin\'></i></a></li> ");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-md-4\'>");
document.writeln("                  <div class=\'copyright\'> <p>&copy; Copyright - SRDS 2020  - All Pictures from <a href=\'https://www.baidu.com/\' title=\'网页模板\' target=\'_blank\'>Internet</a></p>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </footer>");
document.writeln("    <!--small footer end-->");