document.writeln("<header class=\'head-section\'>");
document.writeln("      <div class=\'navbar navbar-default navbar-static-top container\'>");
document.writeln("          <div class=\'navbar-header\'>");
document.writeln("			  <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\'>");
document.writeln("					<span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("			  </button>");
document.writeln("              <a class=\'navbar-brand\' href=\'index.html\'><img src=\'img/logo.png\' width=\"170\"> </a>");
document.writeln("          </div>");
document.writeln("          <div class=\'navbar-collapse collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("              <ul class=\'nav navbar-nav\'>");
document.writeln("                  <li class=\'dropdown\'><a href=\'index.html\'>Home  </a> </li>");
document.writeln("				  <!-- CALLS -->");
document.writeln("				  <li class=\'dropdown\'>");
document.writeln("                      <a class=\'dropdown-toggle\' data-close-others=\'false\' data-delay=\'0\' data-hover=\'dropdown\' data-toggle=\'dropdown\' href=\'call-summary.html\'>Call <i class=\'fa fa-angle-down\'></i>");
document.writeln("                      </a>");
document.writeln("                      <ul class=\'dropdown-menu\'>");
document.writeln("                          <li> <a href=\'call-papers.html\'>Call for Paper</a></li>");
document.writeln("                          <li> <a href=\'call-workshops.html\'>Call for Workshop Proposals</a></li>");
document.writeln("                          <li> <a href=\'call-poster&demos.html\'>Call for Poster and Demos</a> </li>");
document.writeln("                          <li> <a href=\'call-phdforum.html\'>Call for PHD Forum</a> </li>");
document.writeln("                      </ul>");
document.writeln("                  </li>");
document.writeln("                  <!-- PROGRAM -->");
document.writeln("				  <li class=\'dropdown\'>");
document.writeln("                      <a class=\'dropdown-toggle\' data-close-others=\'false\' data-delay=\'0\' data-hover=\'dropdown\' data-toggle=\'dropdown\' href=\'program-summary.html\'>Programs <i class=\'fa fa-angle-down\'></i>");
document.writeln("                      </a>");
document.writeln("                      <ul class=\'dropdown-menu\'>");
document.writeln("                          <li> <a href=\'conference_program.html\'>Conference Program</a></li>");
document.writeln("                          <li> <a href=\'keynote.html\'>Keynotes</a></li>");
document.writeln("                          <li> <a href=\'workshops.html\'>Workshops</a> </li>");
document.writeln("                          <li> <a href=\'invited_tutorial.html\'>Invited Tutorial</a> </li>");
document.writeln("						  <li> <a href=\'accepted_papers.html\'>Accepted Papers</a> </li>");
document.writeln("                      </ul>");
document.writeln("                  </li>");
document.writeln("				  <!-- SUBMISSION -->");
document.writeln("				  <li><a href=\'submission.html\'>Submission</a></li>");
document.writeln("				  <!-- COMMITTEES -->");
document.writeln("				  <li><a href=\'committees.html\'>Committees</a></li>");
document.writeln("<!--");
document.writeln("				  <li class=\'dropdown\'>");
document.writeln("                      <a class=\'dropdown-toggle\' data-close-others=\'false\' data-delay=\'0\' data-hover=\'dropdown\' data-toggle=\'dropdown\' href=\'#\'>Committees <i class=\'fa fa-angle-down\'></i>");
document.writeln("                      </a>");
document.writeln("                      <ul class=\'dropdown-menu\'>");
document.writeln("                          <li> <a href=\'#\'>Organization Committee</a></li>");
document.writeln("                          <li> <a href=\'#\'>Program Committee</a></li>");
document.writeln("                      </ul>");
document.writeln("                  </li>");
document.writeln("-->");
document.writeln("				  <!-- WORKSHOPS -->");
document.writeln("				  <li><a href=\'workshops.html\'>Workshops</a></li>");
document.writeln("				  <!-- ATTEND -->");
document.writeln("				  <li class=\'dropdown\'>");
document.writeln("                      <a class=\'dropdown-toggle\' data-close-others=\'false\' data-delay=\'0\' data-hover=\'dropdown\' data-toggle=\'dropdown\' href=\'attend-summary.html\'>Attendance <i class=\'fa fa-angle-down\'></i>");
document.writeln("                      </a>");
document.writeln("                      <ul class=\'dropdown-menu\'>");
document.writeln("                          <li> <a href=\'venue.html\'>Venue</a></li>");
document.writeln("                          <li> <a href=\'registration.html\'>Registration</a></li>");
document.writeln("						  <li> <a href=\'accommodations.html\'>Accommodations</a></li>");
document.writeln("                          <li> <a href=\'cultural_life.html\'>Cultural Life</a></li>");
document.writeln("						  <li> <a href=\'student_grants.html\'>Student Grants</a></li>");
document.writeln("                      </ul>");
document.writeln("                  </li>");
document.writeln("				  <!-- ABOUT -->");
document.writeln("                  <li class=\'dropdown\'>");
document.writeln("                      <a class=\'dropdown-toggle\' data-close-others=\'false\' data-delay=\'0\' data-hover=\'dropdown\' data-toggle=\'dropdown\' href=\'about-summary.html\'>About <i class=\'fa fa-angle-down\'></i>");
document.writeln("                      </a>");
document.writeln("                      <ul class=\'dropdown-menu\'>");
document.writeln("                          <li> <a href=\'about-past_symposia.html\'>Past Symposia</a></li>");
document.writeln("                          <li> <a href=\'about-sponsors.html\'>Sponsors</a></li>");
document.writeln("                          <li><a href=\'about-contact.html\'>Contact</a> </li>");
document.writeln("                      </ul>");
document.writeln("                  </li>");
document.writeln("              </ul>");
document.writeln("          </div>");
document.writeln("      </div>");
document.writeln("    </header>");